### ISSUE TITLE
sudoers / cmd visudo

### ISSUE THREAD

**Issue by jack-pepper** [yahyaeb/Born2BeRoot#1]
Editing the sudoers directly is considered bad practise and can be dangerous, as one could potentially block themselves from root privileges. Using the command visudo as root will first check the buffered sudoers for syntax errors and allows to add privileges to an user in a safer way.

**Comment by yahyaeb** [comment]
Great observation. Thanks, Morgan!

**Comment by yahyaeb** [comment]
I've updated the README to explain why visudo is the correct and recommended approach, **especially on production servers**. I highlighted the risks of editing the sudoers file directly and clarified that, **for this project**, testing direct edits is acceptable to explore potential issues since the server can easily be reset.

Let me know if you think there’s anything else I should clarify further!
